apiVersion: batch/v1
kind: Job
metadata:
  name: thirdpod
spec:
  template:
    spec:
      containers:
        - name: thirdpod
          image: alessandrodimatteo97/thirdpod
      restartPolicy: Never
  backoffLimit: 4
